### ISSUE TITLE
improve the headtracking functionality

### ISSUE THREAD

**Issue by mattkubota** [willowtreeapps/vocable-ios#20]
**Current behavior:** The cursor on the screen is tracked to your head position and selecting UI is dependant on resting your gaze on an element for a set duration. Because of how small some of the buttons may be and the varying physical abilities of our intended audience, the fast and jerky movement of the cursor is not ideal.

**Desired behavior:** The cursor should feel 1:1 to your head movement with relatively low latency, and it should also feel smooth and stable. For example, if I am looking at a singular point on the screen, my head may be moving ever so slightly. The tracking functionality will pick up on these small movements, but the tracking should be smart enough to know that this wasn't an intended movement. The movement from one area of the screen to the other should also feel smooth and eased.

**Notes:**
- adding easing to the animation
- adding a threshold for velocity in a specific direction before the cursor is tracking and then the tracking will catch back up 1:1

**Comment by jennydoesthings** [comment]
This feels no longer relevant with recent improvements.
